# Generated by Django 4.1.6 on 2023-02-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vancouver_transit_analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="stop_code",
            field=models.IntegerField(null=True),
        ),
    ]
