# Generated by Django 4.1.6 on 2023-02-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vancouver_transit_analyzer", "0003_datapoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="datapoint",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="datapoint",
            name="time",
            field=models.TimeField(auto_now=True),
        ),
    ]
