# Generated by Django 4.1.6 on 2023-02-05 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vancouver_transit_analyzer", "0004_datapoint_date_datapoint_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stop",
            name="stop_code",
        ),
    ]
